### ISSUE TITLE
Incorrect path specified

### ISSUE THREAD

**Issue by Jouveer** [LeaPhant/flowabot#4]
When running a command sequence such as:
!top Vaxei
!render strains 20s

Video encoding fails because there is a space in path due to the windows username.

[2019-07-10T16:56:25.676Z] { Error: Command failed: **C:\Users\Jouveer Naidoo**\Desktop\osu!Bot\flowabot\node_modules\ffmpeg-static\bin\win32\x64\ffmpeg.exe -loop 1 -r 60 -i "C:\tmp\frames\403990016\map\bg.png" -f image2 -r 60 -s 400x300 -pix_fmt rgba -c:v rawvideo -i /tmp/frames/403990016/%d.rgba -ss 261.1 -i "C:\tmp\frames\403990016\map\audio.mp3" -filter:a "afade=t=out:st=31:d=0.5,atempo=1.5,volume=0.7" -filter_complex "overlay=(W-w)/2:shortest=1" -pix_fmt yuv420p -r 60 -c:v libx264 -b:v 2184.5333333333333k -c:a aac -shortest -preset veryfast /tmp/frames/403990016/video.mp4

'C:\Users\Jouveer' is not recognized as an internal or external command,
operable program or batch file.

Windows 10 operating system

**Comment by LeaPhant** [comment]
https://github.com/LeaPhant/flowabot/commit/04519e4a0886cd675b94f39e7ebe0ebddb0a331f should fix this. 

I was also using hardcoded /tmp paths which wouldn't have worked on Windows anyway.

Please try and report back cause I have no Windows machine to test on.

**Comment by Jouveer** [comment]
Pulled and installed the latest version and still get the same error

**Comment by Jouveer** [comment]
Got this to work with #9
